# === Secrets / Credentials ===
api_id = st.secrets.get("TELEGRAM_API_ID", None) or 21469101
api_hash = st.secrets.get("TELEGRAM_API_HASH", None) or "3088140cd7e561ecdadcfbd9871cf3f0"
session_name = "session_utama"
wib = ZoneInfo("Asia/Jakarta")
